services:
  rabbit:
    image: rabbitmq:3.12-management-alpine
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'

networks:
  # This external network allows FDW connections between H, LMS and report DBs.
  # To avoid having unnecessary dependencies between the projects
  # the network is created with `docker network create dbs` in each project's Makefile (make services)
  dbs:
    name: dbs
    external: true
  elasticsearch:
    name: elasticsearch
    external: true
  
